// This file is part of https://github.com/KurtBoehm/thesauros.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#ifndef INCLUDE_THESAUROS_MACROPOLIS_HELPERS_HPP
#define INCLUDE_THESAUROS_MACROPOLIS_HELPERS_HPP

#include "boost/preprocessor.hpp"

#include "thesauros/string/static-string.hpp"

namespace thes {
#define THES_POLIS_STR(STR) \
  ::thes::StaticString { \
    STR \
  }

#define THES_POLIS_ADD_COMMA(ELEM) ELEM,
#define THES_POLIS_TYPED_TO_VARARGS(ELEM) THES_POLIS_ADD_COMMA ELEM

#define THES_POLIS_CALL_TYPED_IMPL(MACRO, ELEM, ...) MACRO(ELEM __VA_OPT__(, __VA_ARGS__))
#define THES_POLIS_CALL_TYPED(MACRO, ELEM, ...) \
  THES_POLIS_CALL_TYPED_IMPL(MACRO, THES_POLIS_TYPED_TO_VARARGS(ELEM) __VA_OPT__(, __VA_ARGS__))

#define THES_POLIS_NAME_KEEP(RAW) RAW
#define THES_POLIS_NAME_LOWERCASE(RAW) RAW
#define THES_POLIS_NAME_NAMED(RAW, NAME) RAW
#define THES_POLIS_NAME_SNAKE_CASE(RAW, ...) RAW
#define THES_POLIS_NAME(ARG) THES_POLIS_NAME_##ARG

#define THES_POLIS_NAME_STR_KEEP(RAW) THES_POLIS_STR(#RAW)
#define THES_POLIS_NAME_STR_LOWERCASE(RAW) THES_POLIS_STR(#RAW)
#define THES_POLIS_NAME_STR_NAMED(RAW, NAME) THES_POLIS_STR(#RAW)
#define THES_POLIS_NAME_STR_SNAKE_CASE(RAW, ...) THES_POLIS_STR(#RAW)
#define THES_POLIS_NAME_STR(ARG) THES_POLIS_NAME_STR_##ARG

#define THES_POLIS_SERIAL_NAME_STR_KEEP(RAW) THES_POLIS_STR(#RAW)
#define THES_POLIS_SERIAL_NAME_STR_LOWERCASE(RAW) THES_POLIS_STR(#RAW).to_lowercase()
#define THES_POLIS_SERIAL_NAME_STR_SNAKE_CASE(RAW, ...) \
  THES_POLIS_STR("_").join(::thes::to_snake_case<THES_POLIS_STR(#RAW)>() \
                             __VA_OPT__(, THES_POLIS_TEMPLATE_MAP(__VA_ARGS__)))
#define THES_POLIS_SERIAL_NAME_STR_NAMED(RAW, NAME) THES_POLIS_STR(BOOST_PP_REMOVE_PARENS(NAME))
#define THES_POLIS_SERIAL_NAME_STR(ARG) THES_POLIS_SERIAL_NAME_STR_##ARG

#define THES_POLIS_TEMPLATE_MAP_INNER(REC, _, IDX, ARG) \
  BOOST_PP_COMMA_IF(IDX)::thes::serial_name_of<ARG>()
#define THES_POLIS_TEMPLATE_MAP_IMPL(LIST) \
  BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_TEMPLATE_MAP_INNER, BOOST_PP_EMPTY(), LIST)
#define THES_POLIS_TEMPLATE_MAP(ARG) \
  THES_POLIS_TEMPLATE_MAP_IMPL(BOOST_PP_VARIADIC_TO_LIST(BOOST_PP_REMOVE_PARENS(ARG)))
} // namespace thes

#endif // INCLUDE_THESAUROS_MACROPOLIS_HELPERS_HPP
