#ifndef INCLUDE_THESAUROS_MACROPOLIS_MEMBERS_HPP
#define INCLUDE_THESAUROS_MACROPOLIS_MEMBERS_HPP

#include <cstddef>

namespace thes {
template<auto tSerialName, auto tValue>
struct StaticMemberInfo {
  static constexpr auto serial_name = tSerialName;
  static constexpr auto value = tValue;
};

template<typename T, auto tName, auto tSerialName, auto tPointer>
struct MemberInfo {
  using Type = T;
  static constexpr auto name = tName;
  static constexpr auto serial_name = tSerialName;
  static constexpr auto pointer = tPointer;
};

template<typename T, auto tName, auto tPointer, std::size_t tOffset>
struct MemberLayoutInfo {
  using Type = T;
  static constexpr auto name = tName;
  static constexpr auto pointer = tPointer;
  static constexpr auto offset = tOffset;
};

template<typename T>
struct MemoryLayoutInfoTrait;

template<typename T>
inline constexpr auto memory_layout_info = MemoryLayoutInfoTrait<T>::members;

template<typename T>
concept HasMemoryLayoutInfo = sizeof(MemoryLayoutInfoTrait<T>) > 0;

template<typename T>
struct TypeInfo;

template<typename T>
requires(requires { typename T::TypeInfo; })
struct TypeInfo<T> {
  using Type = T;
  using Info = Type::TypeInfo;
  using Members = Info::Members;

  static constexpr auto name = Info::name;
  static constexpr auto serial_name = Info::serial_name;
  static constexpr auto static_members = Info::static_members;
  static constexpr auto members = Info::members;
};

template<typename T>
requires(requires { sizeof(TypeInfo<T>); })
inline constexpr auto serial_name_of() {
  return TypeInfo<T>::serial_name;
}

#define THES_POLIS_MEMBER_NAME_STR_IMPL(NAME, TYPE, ...) THES_POLIS_NAME_STR_##NAME
#define THES_POLIS_MEMBER_NAME_STR(ARG) THES_POLIS_MEMBER_NAME_STR_IMPL ARG

#define THES_POLIS_MEMBER_SERIAL_NAME_STR_IMPL(NAME, TYPE, ...) THES_POLIS_SERIAL_NAME_STR_##NAME
#define THES_POLIS_MEMBER_SERIAL_NAME_STR(ARG) THES_POLIS_MEMBER_SERIAL_NAME_STR_IMPL ARG

#define THES_POLIS_MEMBER_NAME_IMPL(NAME, TYPE, ...) THES_POLIS_NAME_##NAME
#define THES_POLIS_MEMBER_NAME(ARG) THES_POLIS_MEMBER_NAME_IMPL ARG

#define THES_POLIS_MEMBER_TYPE_IMPL(NAME, TYPE, ...) BOOST_PP_REMOVE_PARENS(TYPE)
#define THES_POLIS_MEMBER_TYPE(ARG) THES_POLIS_MEMBER_TYPE_IMPL ARG

#define THES_POLIS_MEMBER_INIT_IMPL(NAME, TYPE, ...) \
  __VA_OPT__(=) BOOST_PP_REMOVE_PARENS(__VA_ARGS__)
#define THES_POLIS_MEMBER_INIT(ARG) THES_POLIS_MEMBER_INIT_IMPL ARG

#define THES_POLIS_MEMBER_CONSTR_INIT_IMPL(NAME, TYPE, ...) \
  __VA_OPT__(=) BOOST_PP_REMOVE_PARENS(__VA_ARGS__)
#define THES_POLIS_MEMBER_CONSTR_INIT(ARG) THES_POLIS_MEMBER_CONSTR_INIT_IMPL ARG

// Generate the static member definitions

#define THES_POLIS_STATIC_MEMBER_IMPL(SERIAL_NAME, VALUE) \
  ::thes::StaticMemberInfo<THES_POLIS_STR(SERIAL_NAME), VALUE> {}
#define THES_POLIS_STATIC_MEMBER(REC, _, IDX, PAIR) \
  BOOST_PP_COMMA_IF(IDX) THES_POLIS_STATIC_MEMBER_IMPL PAIR

// A member declaration

#define THES_POLIS_MEMBER_DECL(REC, TYPENAME, ARG) \
  THES_POLIS_MEMBER_TYPE(ARG) THES_POLIS_MEMBER_NAME(ARG) THES_POLIS_MEMBER_INIT(ARG);

// Body parts

#define THES_POLIS_BODIES(REC, DUMMY, BODY) BOOST_PP_REMOVE_PARENS(BODY)

// Generate the MemberInfos

#define THES_POLIS_MEMBER_INFO(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) \
  ::thes::MemberInfo<THES_POLIS_MEMBER_TYPE(ELEM), THES_POLIS_MEMBER_NAME_STR(ELEM), \
                     THES_POLIS_MEMBER_SERIAL_NAME_STR(ELEM), \
                     &TYPENAME::THES_POLIS_MEMBER_NAME(ELEM)> {}

// Generate the template params

#define THES_POLIS_TEMPLATE_PARAM_IMPL(TYPE, NAME) TYPE NAME##Inner
#define THES_POLIS_TEMPLATE_PARAM(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) THES_POLIS_CALL_TYPED(THES_POLIS_TEMPLATE_PARAM_IMPL, ELEM)

#define THES_POLIS_TEMPLATE_PARAM_VALUE_IMPL(TYPE, NAME) NAME##Inner
#define THES_POLIS_TEMPLATE_PARAM_VALUE(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) \
  THES_POLIS_CALL_TYPED(THES_POLIS_TEMPLATE_PARAM_VALUE_IMPL, ELEM)

#define THES_POLIS_DEFINE_TEMPLATE_TYPE(TYPENAME, TEMPLATE_PARAMS) \
  template<BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_TEMPLATE_PARAM, TYPENAME, TEMPLATE_PARAMS)> \
  using TemplateType = TYPENAME<BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_TEMPLATE_PARAM_VALUE, \
                                                         TYPENAME, TEMPLATE_PARAMS)>;

#define THES_POLIS_TEMPLATE_SPEC_PARAM_IMPL(TYPE, NAME) TYPE NAME
#define THES_POLIS_TEMPLATE_SPEC_PARAM(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) THES_POLIS_CALL_TYPED(THES_POLIS_TEMPLATE_SPEC_PARAM_IMPL, ELEM)
#define THES_POLIS_TEMPLATE_SPEC(TYPENAME, TEMPLATE_PARAMS) \
  template<BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_TEMPLATE_SPEC_PARAM, TYPENAME, TEMPLATE_PARAMS)>

#define THES_POLIS_TEMPLATE_SPEC_PARAM_NAME_IMPL(TYPE, NAME) NAME
#define THES_POLIS_TEMPLATE_SPEC_PARAM_NAME(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) \
  THES_POLIS_CALL_TYPED(THES_POLIS_TEMPLATE_SPEC_PARAM_NAME_IMPL, ELEM)
#define THES_POLIS_TEMPLATE_SPEC_NAMES(TYPENAME, TEMPLATE_PARAMS) \
<BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_TEMPLATE_SPEC_PARAM_NAME, TYPENAME, TEMPLATE_PARAMS)>

// Generate the namespace

#define THES_POLIS_NAMESPACE_IMPL(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_IF(IDX, ::, BOOST_PP_EMPTY()) ELEM
#define THES_POLIS_NAMESPACE(NAMESPACES) \
  BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_NAMESPACE_IMPL, BOOST_PP_EMPTY, NAMESPACES)

// Generate the member offsets

#define THES_POLIS_MEMBER_OFFSET(REC, TYPENAME, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) \
  MemberLayoutInfo<THES_POLIS_MEMBER_TYPE(ELEM), THES_POLIS_MEMBER_NAME_STR(ELEM), \
                   &TYPENAME::THES_POLIS_MEMBER_NAME(ELEM), \
                   offsetof(TYPENAME, THES_POLIS_MEMBER_NAME(ELEM))> {}

// The constructor implementation

#define THES_POLIS_CONSTRUCTOR_PARAMS(REC, TYPENAME, IDX, ARG) \
  BOOST_PP_COMMA_IF(IDX) \
  THES_POLIS_MEMBER_TYPE(ARG) \
  BOOST_PP_CAT(p_, THES_POLIS_MEMBER_NAME(ARG)) THES_POLIS_MEMBER_CONSTR_INIT(ARG)

#define THES_POLIS_CONSTRUCTOR_INIT_LIST(REC, TYPENAME, IDX, ARG) \
  BOOST_PP_COMMA_IF(IDX) \
  THES_POLIS_MEMBER_NAME(ARG) { \
    std::move(BOOST_PP_CAT(p_, THES_POLIS_MEMBER_NAME(ARG))) \
  }

#define THES_POLIS_CONSTRUCTOR_DEF_IMPL(TYPENAME, LIST)  : BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_CONSTRUCTOR_INIT_LIST, TYPENAME, LIST)
#define THES_POLIS_CONSTRUCTOR_DEF(TYPENAME, LIST) \
  TYPENAME(BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_CONSTRUCTOR_PARAMS, TYPENAME, LIST)) \
  BOOST_PP_REMOVE_PARENS(BOOST_PP_IIF(BOOST_PP_LIST_IS_NIL(LIST), (), \
                                      (THES_POLIS_CONSTRUCTOR_DEF_IMPL(TYPENAME, LIST)))) {}

// Constructor case distinction

#define THES_POLIS_TYPE_CONSTEXPR_CONSTRUCTOR(TYPENAME, LIST) \
  explicit constexpr THES_POLIS_CONSTRUCTOR_DEF(TYPENAME, LIST)
#define THES_POLIS_TYPE_NORMAL_CONSTRUCTOR(TYPENAME, LIST) \
  explicit THES_POLIS_CONSTRUCTOR_DEF(TYPENAME, LIST)
#define THES_POLIS_TYPE_NO_CONSTRUCTOR(TYPENAME, LIST)
#define THES_POLIS_CONSTRUCTOR(TYPENAME, CONSTRUCTOR, LIST) \
  THES_POLIS_TYPE_##CONSTRUCTOR(TYPENAME, LIST)

// Split definitions

#define THES_POLIS_NAMESPACE_FILTER_PRED_NAMESPACE(...) 1
#define THES_POLIS_NAMESPACE_FILTER_PRED_STATIC_MEMBERS(...) 0
#define THES_POLIS_NAMESPACE_FILTER_PRED_MEMBERS(...) 0
#define THES_POLIS_NAMESPACE_FILTER_PRED_TEMPLATE_PARAMS(...) 0
#define THES_POLIS_NAMESPACE_FILTER_PRED_BODY(...) 0

#define THES_POLIS_STATIC_MEMBERS_FILTER_PRED_NAMESPACE(...) 0
#define THES_POLIS_STATIC_MEMBERS_FILTER_PRED_STATIC_MEMBERS(...) 1
#define THES_POLIS_STATIC_MEMBERS_FILTER_PRED_MEMBERS(...) 0
#define THES_POLIS_STATIC_MEMBERS_FILTER_PRED_TEMPLATE_PARAMS(...) 0
#define THES_POLIS_STATIC_MEMBERS_FILTER_PRED_BODY(...) 0

#define THES_POLIS_MEMBERS_FILTER_PRED_NAMESPACE(...) 0
#define THES_POLIS_MEMBERS_FILTER_PRED_STATIC_MEMBERS(...) 0
#define THES_POLIS_MEMBERS_FILTER_PRED_MEMBERS(...) 1
#define THES_POLIS_MEMBERS_FILTER_PRED_TEMPLATE_PARAMS(...) 0
#define THES_POLIS_MEMBERS_FILTER_PRED_BODY(...) 0

#define THES_POLIS_TEMPLATE_PARAMS_FILTER_PRED_NAMESPACE(...) 0
#define THES_POLIS_TEMPLATE_PARAMS_FILTER_PRED_STATIC_MEMBERS(...) 0
#define THES_POLIS_TEMPLATE_PARAMS_FILTER_PRED_MEMBERS(...) 0
#define THES_POLIS_TEMPLATE_PARAMS_FILTER_PRED_TEMPLATE_PARAMS(...) 1
#define THES_POLIS_TEMPLATE_PARAMS_FILTER_PRED_BODY(...) 0

#define THES_POLIS_BODY_FILTER_PRED_NAMESPACE(...) 0
#define THES_POLIS_BODY_FILTER_PRED_STATIC_MEMBERS(...) 0
#define THES_POLIS_BODY_FILTER_PRED_MEMBERS(...) 0
#define THES_POLIS_BODY_FILTER_PRED_TEMPLATE_PARAMS(...) 0
#define THES_POLIS_BODY_FILTER_PRED_BODY(...) 1

#define THES_POLIS_ANY_MEMBERS_FILTER_OP_NAMESPACE(...) __VA_ARGS__
#define THES_POLIS_ANY_MEMBERS_FILTER_OP_STATIC_MEMBERS(...) __VA_ARGS__
#define THES_POLIS_ANY_MEMBERS_FILTER_OP_MEMBERS(...) __VA_ARGS__
#define THES_POLIS_ANY_MEMBERS_FILTER_OP_TEMPLATE_PARAMS(...) __VA_ARGS__
#define THES_POLIS_ANY_MEMBERS_FILTER_OP_BODY(...) __VA_ARGS__

#define THES_POLIS_ANY_MEMBERS_FILTER_PRED(REC, KIND, ELEM) THES_POLIS_##KIND##_FILTER_PRED_##ELEM
#define THES_POLIS_ANY_MEMBERS_FILTER_OP_IMPL(ELEM) THES_POLIS_ANY_MEMBERS_FILTER_OP_##ELEM
#define THES_POLIS_ANY_MEMBERS_FILTER_OP(REC, KIND, IDX, ELEM) \
  BOOST_PP_COMMA_IF(IDX) THES_POLIS_ANY_MEMBERS_FILTER_OP_IMPL(ELEM)

#define THES_POLIS_ANY_MEMBERS_FILTER_UNPACK(...) BOOST_PP_VARIADIC_TO_LIST(__VA_ARGS__)
#define THES_POLIS_ANY_MEMBERS_FILTER_IMPL(KIND, LIST) \
  THES_POLIS_ANY_MEMBERS_FILTER_UNPACK( \
    BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_ANY_MEMBERS_FILTER_OP, KIND, LIST))
#define THES_POLIS_ANY_MEMBERS_FILTER(KIND, LIST) \
  THES_POLIS_ANY_MEMBERS_FILTER_IMPL( \
    KIND, BOOST_PP_LIST_FILTER(THES_POLIS_ANY_MEMBERS_FILTER_PRED, KIND, LIST))

// The main definitions

#define THES_APPLY(MACRO, ...) MACRO(__VA_ARGS__)

// TODO NAMESPACES is ignored, but there is no point here anyway…
#define THES_DEFINE_TYPE_IMPL(TYPE, TYPENAME, CONSTRUCTOR, NAMESPACES, TEMPLATE_PARAMS, \
                              STATIC_MEMBERS, MEMBERS, BODIES) \
  THES_POLIS_CONSTRUCTOR(TYPENAME, CONSTRUCTOR, MEMBERS) \
  BOOST_PP_LIST_FOR_EACH(THES_POLIS_MEMBER_DECL, TYPENAME, MEMBERS) \
  struct TypeInfo { \
    using Type = TYPENAME; \
    BOOST_PP_REMOVE_PARENS(BOOST_PP_IIF(BOOST_PP_LIST_IS_NIL(TEMPLATE_PARAMS), (), \
                                        (THES_POLIS_DEFINE_TEMPLATE_TYPE(TYPENAME, \
                                                                         TEMPLATE_PARAMS)))) \
    static constexpr auto name = THES_POLIS_NAME_STR(TYPE); \
    static constexpr auto serial_name = THES_POLIS_SERIAL_NAME_STR(TYPE); \
\
    static constexpr std::tuple members{ \
      BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_MEMBER_INFO, TYPENAME, MEMBERS)}; \
    static constexpr std::tuple static_members{ \
      BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_STATIC_MEMBER, BOOST_PP_EMPTY(), STATIC_MEMBERS)}; \
\
    using Members = decltype(members); \
  }; \
  BOOST_PP_LIST_FOR_EACH(THES_POLIS_BODIES, TYPENAME, BODIES)

#define THES_CREATE_TYPE_IMPL_INNER(TYPE, TYPENAME, FULL_NAME, CONSTRUCTOR, NAMESPACES, \
                                    TEMPLATE_PARAMS, STATIC_MEMBERS, MEMBERS, BODIES) \
  BOOST_PP_IIF( \
    BOOST_PP_LIST_IS_NIL(NAMESPACES), BOOST_PP_EMPTY(), \
    namespace THES_POLIS_NAMESPACE(NAMESPACES) {) \
  BOOST_PP_REMOVE_PARENS(BOOST_PP_IIF(BOOST_PP_LIST_IS_NIL(TEMPLATE_PARAMS), (), \
                                      (THES_POLIS_TEMPLATE_SPEC(TYPENAME, TEMPLATE_PARAMS)))) \
  struct TYPENAME { \
        THES_DEFINE_TYPE_IMPL(TYPE, TYPENAME, CONSTRUCTOR, NAMESPACES, TEMPLATE_PARAMS, \
                              STATIC_MEMBERS, MEMBERS, BODIES) \
      }; \
  BOOST_PP_IIF(BOOST_PP_LIST_IS_NIL(NAMESPACES), BOOST_PP_EMPTY(), \
    }) \
\
  THES_POLIS_TEMPLATE_SPEC(TYPENAME, TEMPLATE_PARAMS) \
  struct thes::MemoryLayoutInfoTrait<BOOST_PP_REMOVE_PARENS(FULL_NAME)> { \
    using Self = BOOST_PP_REMOVE_PARENS(FULL_NAME); \
    static constexpr std::tuple members{ \
      BOOST_PP_LIST_FOR_EACH_I(THES_POLIS_MEMBER_OFFSET, Self, MEMBERS)}; \
  };

#define THES_CREATE_TYPE_IMPL(TYPE, TYPENAME, CONSTRUCTOR, NAMESPACES, TEMPLATE_PARAMS, \
                              STATIC_MEMBERS, MEMBERS, BODIES) \
  THES_CREATE_TYPE_IMPL_INNER(TYPE, TYPENAME, \
                              (BOOST_PP_IIF(BOOST_PP_LIST_IS_NIL(NAMESPACES), BOOST_PP_EMPTY(), \
                                            THES_POLIS_NAMESPACE(NAMESPACES)::) \
                                 TYPENAME BOOST_PP_REMOVE_PARENS(BOOST_PP_IIF( \
                                   BOOST_PP_LIST_IS_NIL(TEMPLATE_PARAMS), (), \
                                   (THES_POLIS_TEMPLATE_SPEC_NAMES(TYPENAME, TEMPLATE_PARAMS))))), \
                              CONSTRUCTOR, NAMESPACES, TEMPLATE_PARAMS, STATIC_MEMBERS, MEMBERS, \
                              BODIES)

#define THES_DEFINE_TYPE(TYPE, CONSTRUCTOR, ...) \
  THES_DEFINE_TYPE_IMPL(TYPE, THES_POLIS_NAME(TYPE), CONSTRUCTOR, BOOST_PP_LIST_NIL, \
                        BOOST_PP_LIST_NIL, BOOST_PP_LIST_NIL, \
                        BOOST_PP_VARIADIC_TO_LIST(__VA_ARGS__), BOOST_PP_LIST_NIL)

#define THES_DEFINE_TYPE_EX_IMPL(IMPL, TYPE, CONSTRUCTOR, LIST) \
  THES_APPLY(IMPL, TYPE, THES_POLIS_NAME(TYPE), CONSTRUCTOR, \
             THES_POLIS_ANY_MEMBERS_FILTER(NAMESPACE, LIST), \
             THES_POLIS_ANY_MEMBERS_FILTER(TEMPLATE_PARAMS, LIST), \
             THES_POLIS_ANY_MEMBERS_FILTER(STATIC_MEMBERS, LIST), \
             THES_POLIS_ANY_MEMBERS_FILTER(MEMBERS, LIST), \
             THES_POLIS_ANY_MEMBERS_FILTER(BODY, LIST))

#define THES_DEFINE_TYPE_EX(TYPE, CONSTRUCTOR, ...) \
  THES_DEFINE_TYPE_EX_IMPL(THES_DEFINE_TYPE_IMPL, TYPE, CONSTRUCTOR, \
                           BOOST_PP_VARIADIC_TO_LIST(__VA_ARGS__))

#define THES_CREATE_TYPE_EX(TYPE, CONSTRUCTOR, ...) \
  THES_DEFINE_TYPE_EX_IMPL(THES_CREATE_TYPE_IMPL, TYPE, CONSTRUCTOR, \
                           BOOST_PP_VARIADIC_TO_LIST(__VA_ARGS__))
} // namespace thes

#endif // INCLUDE_THESAUROS_MACROPOLIS_MEMBERS_HPP
