#ifndef INCLUDE_THESAUROS_OPTIMIZATION_HPP
#define INCLUDE_THESAUROS_OPTIMIZATION_HPP

#define THES_ALWAYS_INLINE __attribute__((always_inline))
#define THES_NEVER_INLINE __attribute__((noinline))

#endif // INCLUDE_THESAUROS_OPTIMIZATION_HPP
