#ifndef INCLUDE_THESAUROS_EXECUTION_EXECUTION_POLICY_HPP
#define INCLUDE_THESAUROS_EXECUTION_EXECUTION_POLICY_HPP

#include "execution-policy/linear.hpp"

#endif // INCLUDE_THESAUROS_EXECUTION_EXECUTION_POLICY_HPP
