#ifndef INCLUDE_THESAUROS_ALGORITHMS_EXECUTION_HPP
#define INCLUDE_THESAUROS_ALGORITHMS_EXECUTION_HPP

#include "execution/transform-inclusive-scan.hpp"

#endif // INCLUDE_THESAUROS_ALGORITHMS_EXECUTION_HPP
